services:
  db:
    image: postgres:16
    container_name: axle_db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: axle
      POSTGRES_PASSWORD: axlepass
      POSTGRES_DB: axle
    volumes:
      - axle_pgdata:/var/lib/postgresql/data

volumes:
  axle_pgdata:


